notARepository: 'quit'
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    inactiveBorderColor:
      - '#4c566a'
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
